### ISSUE TITLE
Hide the Latex and Greek Letters

### ISSUE THREAD

**Issue by PaulHerrero** [Reocin/obsidian-markdown-formatting-assistant-plugin#15]
I hope I can hide the Latex and Greek Letters because I don't need them. Thanks.

**Comment by Reocin** [comment]
Hello @PaulHerrero 

Thanks for your request. At the moment not, but i'm already on it. Actually i wanted to add a collapse possibility so that you see the headers, but you would have to klick to see the content. However, your idea with an option to hide them in the Settings is also good and i will think about it. Probably with a option to sort them in the users flavour.

**Comment by PaulHerrero** [comment]
Thank you for your reply. Both methods are fine, as long as the unused modules don't take up a lot of space.

**Comment by Reocin** [comment]
So. I had some trouble with this part, but finally I managed it. The sections now expandable and can be ordered via drop and catch. An example can be viewed in the README file. If you really want to disable a section, this can be done in the settings.

Sorry for my late implementation, but I had so much going on in work.

Regards Daniel

**Comment by PaulHerrero** [comment]
Thank you very much
