### ISSUE TITLE
The plug-in didn't work

### ISSUE THREAD

**Issue by iFryRice** [Reocin/obsidian-markdown-formatting-assistant-plugin#47]
**Describe the bug**
When I turned on the plug-in, neither the menu bar nor the Trigger worked.If it‘s Ok，hope to receive your answer.

**Expected behavior**
Hope can return to normal use.

**Screenshots**
![image](https://user-images.githubusercontent.com/102138235/159845084-a9bdc238-1435-4383-8625-9e41485af672.png)
![image](https://user-images.githubusercontent.com/102138235/159844805-37a7fefb-4d3d-4b1e-9235-b56e34e926fd.png)
![image](https://user-images.githubusercontent.com/102138235/159845080-4fe8a056-ce42-4b5d-8fbc-c41b8df57c1c.png)

**Desktop (please complete the following information):**
 - OS: Win11
 - App: Obsidian v0.13.33
 - Plugin Version: 0.3.2

**Comment by Reocin** [comment]
PS: Your problem could also because of the theme. Please try it again with the default theme.
----
Hey guys, it is just a quick fix, but the plugin should work again. **Please make sure that you use an obsidian version 0.15.x and update the plugin to the version 0.4.0**

Read also read the README for the new replacement of the trigger command `\`. It works now with the hotkey `ALT+Q` (it is just a quick update of the README. I will go through on another day)
