### ISSUE TITLE
Not working anymore with Obsidian 0.15.6

### ISSUE THREAD

**Issue by rattlesnake2028** [Reocin/obsidian-markdown-formatting-assistant-plugin#54]
**Describe the bug**
In Obsidian 0.15.6, the buttons does'nt provides any effect.
Maybe because of this : 
Developers => Refer to https://forum.obsidian.md/t/plugin-developers-how-to-update-your-plugin-to-support-pop-out-windows/40228 for ensuring your plugin is compatible with pop-out windows.

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by SimoAbjaou** [comment]
I have the same issue. Please update the plugin to be compatible with the new obsidian version because I use it all day everyday.

**Comment by RollOfDeath** [comment]
I got the same issue.

OS: Garuda Linux 
Kernel: 5.18.9-zen1-1-zen

**Comment by 93chanle** [comment]
I also got the same issue with Obsidian 0.15.6 and Windows 11.

**Comment by ksdavidc** [comment]
I can confirm this on mac

**Comment by leonardosalatino** [comment]
I also confirm the issue on windows 10 and kubuntu 22.04

**Comment by zcyh147** [comment]
same here, macOS big sur + obsidian 0.15.6

**Comment by VonChair** [comment]
Confirmed on Mac OS 12.5 Intel version with Obsidian Version 0.15.6 suffers the same issue.

**Comment by Alilat-imad** [comment]
I also confirm the issue.

**Comment by hisel-sabermetrics** [comment]
Can confirm this on M1 Mac Monterey 12.4 with obsidian 15.8

**Comment by mathisgauthey** [comment]
Confirmed in 0.15.8, nothing is working.

**Comment by rdricco** [comment]
Confirmed on Manjaro too.

**Comment by leonardosalatino** [comment]
Seems that this plugin doesn't have any support, right? I see the last changes were done 14 months ago.

**Comment by naichaduck** [comment]
same issue

**Comment by naichaduck** [comment]
> **Describe the bug** In Obsidian 0.15.6, the buttons does'nt provides any effect. Maybe because of this : Developers => Refer to https://forum.obsidian.md/t/plugin-developers-how-to-update-your-plugin-to-support-pop-out-windows/40228 for ensuring your plugin is compatible with pop-out windows.
> 
> **Desktop (please complete the following information):**
> 
>     * OS: Windows 10

Have you found a solution?

**Comment by rattlesnake2028** [comment]
Well Guys, this plugin seems to not be supported anymore.
I use another plugin called cMenu which works very well !

**Comment by wei-seven** [comment]
I also got the same issue with Obsidian 0.15.9 and Windows 11.

**Comment by WystanW** [comment]
> Well Guys, this plugin seems to not be supported anymore. I use another plugin called cMenu which works very well !

However, I think cMenu has fewer features than this.

**Comment by Reocin** [comment]
Hey Guys. Sorry for my absence. I had no time to do any private codeing because of my new job, but i working on it. I already find a solution for the side pane, but the trigger command is really hard. They changed a lot in the API and the documentation is awful. 

I need a little more time to solve the solution.

**Comment by SimoAbjaou** [comment]
Really good news, I downgrade to the older version specially for this plugin and waiting for new update.  Good Luck.

**Comment by Reocin** [comment]
@SimoAbjaou that's perfect ;-) 

@all
Last night also found a solution for the trigger command. It won't be a char trigger any more like before. I changed it to the hotkey "Alt+Q" (has no meaning, just because you can reach it quickly with one hand and can be changed in the inbuilt hotkey mapping of obsidian) and use a Obsidian [Suggestion modal.](https://marcus.se.net/obsidian-plugin-docs/user-interface/modals#select-from-list-of-suggestions) With this, you can really quickly access all the shortcuts of my plugin without leaving the keyboard.

Now i have to clean up the code and also update the rest of the code to the new API. I hope I don't find any more time intensive problems.

I hope to release the first quick fix this or next week.

**Comment by Reocin** [comment]
Hey guys, it is just a quick fix, but the plugin should work again. **Please make sure that you use an obsidian version 0.15.x and update the plugin to the version 0.4.0**

Read also read the README for the new replacement of the trigger command `\`. It works now with the hotkey `ALT+Q` (it is just a quick update of the README. I will go through on another day)

**Comment by ovizii** [comment]
Seems broken again with Obsidian 1.1.16 and your plugin version 0.4.1 - I think there is also confusion because in your plugin's settings you are speaking about "trigger char" for autocompletion and in your README you are talking about a shortcut for the suggestion window. From what I am reading here in this thread, its one and the same functionality? 

Or are these 2 different things? I can confirm that "\" apparently seems to do nothing while ALT+Q and ALT+C work.
